---
sudo: false
language: ruby
cache: bundler
bundler_args: --path ../../vendor/bundle --without debug
env:
  global:
    - TRAVIS=1
before_install: gem install bundler -v 2.0.1
script: bundle exec rspec
matrix:
  include:
    - name: Rubocop
      gemfile: spec/gemfiles/rubocop.gemfile
      rvm: 2.6.3
      script: bundle exec rubocop
    - gemfile: spec/gemfiles/rails_5_2.gemfile
      rvm: 2.3.8
    - gemfile: spec/gemfiles/rails_6_0.gemfile
      rvm: 2.5.5
