name: Publish Package to npmjs
on:
  release:
    types: [published]
    branches:
      - nodejs-sqlcommenter
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
                               
      # Publish SQLCommenter Sequelize        
      - run: npm ci
        working-directory: ./packages/sqlcommenter-knex

      - run: npm publish --access public
        working-directory: ./packages/sqlcommenter-knex
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
       